### ISSUE TITLE
Add rollbar error tracking

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#1107]
Need to add rollbar error tracking so we can know when the SDK panics and why.

- [x] Create separate rollbar projects for prod and staging
- [x] Integrate into UI
- [x] Add env vars to production and staging vercel
- [x] Redeploy
