### ISSUE TITLE
🇵🇱 Polish checklist

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#422]
### Functional
- [x] Make long rows clickable and open modal. Remove "Close" button. @DannyDelott
- [x] Change Long columns to "Position", "Size (hyBASE)", "Amount paid (BASE)", "Value (BASE)", "Value at Maturity (BASE)", "Matures on" @DannyDelott 
- [x] Update closed long table @DannyDelott 
![image](https://github.com/delvtech/hyperdrive-monorepo/assets/4524175/18f5f9d1-0387-4903-ae13-f701d4518066)
- [x] **Priority: Make shorts rows clickable and open modal. Remove "Close" button. @jackburrus**
- [x] Change Short columns to "Size (hyBASE)", "Price of hyToken at open", "Amount paid", ~~"Current price"~~(visible in market stats), ~~"Accrued yield"~~ (ask about this one), "Current value (+/- PnL)" @jackburrus  
- [x] ~~Make LP/Withdrawal Shares rows clickable. Remove "Close" button. @jackburrus~~ wontdo
- [x] Transaction table: Add filtering a la Uniswap for "All", "Buys", "Sells", "Shorts", "LP" @jackburrus 
- [x] All Markets table: Refactor to react-table, update rows to match market stats @jackburrus 

### Cosmetic
- [x] lightmode refactor to (`lofi` daisy theme), cleaning up any broken styles from hardcoded dark mode theme, eg: `text-white` vs `text-base-content`. This is present in tooltips and modals. @DannyDelott 
- [x] Refactor text inputs to use DaisyUI components instead of custom logic in `TokenInput`, example: @DannyDelott 
<img width="303" alt="image" src="https://github.com/delvtech/hyperdrive-monorepo/assets/4524175/34ade5b5-089d-4d65-a4a2-9d6996d7a31b">

- [x] Rename all usages of `bonds` to `hy${base}`
- [x] Polish open long/short/lp modals a bit, spruce them up and make them consistent @DannyDelott
- [x] Add "[NonIdealState](https://blueprintjs.com/docs/#core/components/non-ideal-state)" to default empty tables w/ CTAs
