### ISSUE TITLE
Feedback checklist

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#446]
### General
- [ ] App freezes and crashes when disconnecting wallet in rainbow modal
- [ ] A full app crash occurred ("BigInt formatting error") after user opened a long and navigated to the Longs tab. The app refreshed itself once the tx cleared and the error was gone.
- [x] Show the volume split by long versus short. Could be in the tooltip when you hover over the market stats. (@jackburrus )
- [ ] Add column sorting on fixed rate and current value column (@jackburrus )

### Longs
- [x] Add `Pool fee` to preview tx stats in open long modal (use curve fee from poolConfig)
- [x] Show WETH value in green daisy badge under `Fixe rate (APR)`
- [x] Make table headers sticky
- [x] Add maturity badge ("days left", "term ended") to open longs table
-  Change `Size (hyBase)` to `Base (Return amount)` (Hold off on this for now)
Question: Should we remove the token name from the column header and put them in each cell, then we can just have `Amount returned` in the header? Or this could just be `hyBase` with an amount returned tooltip.

### Shorts
- [ ] New Column: Show `Fixed rate shorted` in Shorts table. (/cc @jalextowle to help calculate this from the OpenShort event, ie: `baseAmount`, `bondAmount`, pool duration in days)
- [x] Add maturity badge ("days left", "term ended") to open shorts table
- [x] New Column: Show "accrued yield" (calculation given from @jrhea here: https://discord.com/channels/754739461707006013/1062553591988113489/1164584741350146189)
- [x] Make table headers sticky

### LP
- [x] Add more `places` to fix dust showing in Withdrawal Shares
- [ ] Show pnl badge under `Current value` (/cc @jalextowle to help calculate this from lpSharePrice info)
- [x] Rename `Pending Withdrawal` to `Withdrawal Shares`
- [x] Make table headers sticky
-  Show the portion that would be withdrawable right after lping in Preview Transaction section (@jackburrus) (*Not currently doable with contract methods, needs hyperwasm)

### Transactions Table
- [ ] Add links to block explorer (add option to AppConfig for this)
- [x] Make table headers sticky

### FAQ
- [x] How does LPing work and what are withdrawal shares?
