### ISSUE TITLE
💅 Polish Checklist

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#572]
### Homepage @DannyDelott 
- [x] More left margin on FAQ questions
- [x] MOBILE: Make the FAQ expandos match the dark blue well (No outline, just reuse the card colors) and the label blue color for the question labels. 
- [x] Add an arrow icon to the yellow View Markets button

### Footer @DannyDelott 
- [x] Switch section labels to use label blue color instead of gray

### Markets List page @jackburrus 
- [x] Add overflow auto to table
- [x] Add tooltips to table headers
- [x] Remove bold on table headers (on Market Details too)
- [x] MOBILE: Add more active space between label/value groups
- [x] MOBILE: Use label blue color for label
- [x] MOBILE: Add green chevron-right so rows appear more interactive

### Market Details page
- [x] Move note from Open Long form into Close Long modal @DannyDelott 
- [x] Move note from Add LP to Close LP modal @DannyDelott 
- [x] Re-use label blue for table label on Transactions and Open positions table @DannyDelott 
- [x] Open Forms: Make BASE label more integrated into input group (use input color as background, border radius, keep vertical separator) @DannyDelott 
- [x] Add space between LP shares and Withdrawal shares card @jackburrus 
- [x] Add tooltips to preview transaction data on form @jackburrus 
- [x] Fix alignment of cell data in Positions tables (make data align to the top of the cell, even on stacked cells) @jackburrus 
- [x] Preview Open Transaction: label colors, better wrapping of preview values @DannyDelott 
	- ~~Longs~~, ~~Shorts~~, ~~LP~~
- [x] Preview Close Transaction: Use modal background for Well w/ subtle outline, blue labels, Green button @jackburrus 
- [x] FAQ: Align question and answer content to the left-hand side @jackburrus 
- [x] MOBILE: More active spacing on market stats @jackburrus 
- [x] MOBILE: Fix border radius on transaction form (currently only on the right side) @jackburrus 

### Misc
- [x] Fix colors on toasts @jackburrus
