### ISSUE TITLE
Polish Checklist No. 2 🇵🇱

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#620]
# Market Details
- [x] Switch to vertical on `lg` breakpoint to avoid smooshing:
![Image](https://github.com/delvtech/hyperdrive-monorepo/assets/4524175/94009316-406b-4600-9f73-1bd0724da4da)
- [x] Add loading spinners to Open and Closed Tables, see #615 
- [x] Add Non-Ideal state instead of empty table to Closed tabs, see #616 
- [x] Transaction table filter tabs should have the same hover treatment for active/inactive tabs as Longs/Shorts/LP ![Image](https://github.com/delvtech/hyperdrive-monorepo/assets/4524175/c645c442-9140-42af-aecb-11e697b1fb66)
- [x] Show "No data" label instead of blank space when LP APY is 0. (Visible on Details page and All Markets table)
- [x] Show Non-Ideal state for empty Transactions table
- [x] Update footer links (will need to collab with legal and product for latest urls)
