### ISSUE TITLE
User Testing Checklist 👨‍🔬

### ISSUE THREAD

**Issue by jackburrus** [delvtech/hyperdrive-frontend#635]
The following checklist is user feedback provided by Greg from Chainsafe. More context on the issues (including screen recordings) can be found here: 
- https://discord.com/channels/754739461707006013/799343723086479421/1203017814445924463
- https://www.notion.so/delv-tech/GregTheGreek-User-Testing-Feb-2-2024-8f340787a48949458bc2be3596528335?pvs=4

- [x] Update styling on tabs in transactions table
- [x] Fix the overflow (needs fixed size?) on Longs/Shorts/LP tabs.
https://github.com/delvtech/hyperdrive-monorepo/assets/22210106/9cfa1169-125f-424b-a741-155d82a97dd5
- [x] Make open position component resizing consistent
https://github.com/delvtech/hyperdrive-monorepo/assets/22210106/bd665d41-ab50-4f05-be23-918c268c0d56
- [x] Disable Open/Closed filter when wallet not connected
- [x] Default sort column on tx table should be block number, not size.
- [x] Label in Add Liquidity form should say "LP Shares" instead of "LP"
- [ ] Add P&L to closed positions (check on feasibility by doing write up about it)
- [x] Screen goes blank after open position tx confirmation (Change this back to invalidate queries?)
- [x] Set a fixed width for form element on opening positions
