### ISSUE TITLE
RageCage feedback checklist

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#775]
- [x] Fix pagination, (All txs table looks right when there is 1 tx (eg: Add Liquidity), but if you look at the Longs tx table, you'll get `Page 1 of 0`. I think filtering the data array isn't making it into the pagination component. @jackburrus  
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/4056a142-e72a-4f14-babe-3d4fedaf8290)

- [x]  Avoid cutting off the dropdown by just making the transaction section a little taller (or explore z-index) @jackburrus 
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/0aa4f183-9119-4568-a413-5899ac06ab96)

- [x] Improve layout/spacing @jackburrus 
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/f0c95b53-4522-4f1a-80fc-ea827a43036c)

- [x] Provide a "Pending transaction" indicator for approvals and hyperdrive txs (toast that stays until resolved)
> Minor detail: after approving dai, nothing seemed to have happened, but then a notification appeared showing it approved. It would be nice if there was an animated thing showing "transaction currently processing" or similar

- [x] Fix tooltip getting cut off on half-screen viewports
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/d53b3d88-7b7d-4e2c-9542-0b4efefe9922)

- [x] Add toast for "Add liquidity pending" and "Remove Liquidity pending" @jackburrus 

- [x]   Remove `.` from sub text:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/3a39a105-ffdc-4db8-bfca-8790d8c6bc6a)

- [x] LP Value isn't the same as preview withdrawal amount, screenshots:
https://discord.com/channels/754739461707006013/1218290587879477250/1218292724755599371

- [x] Skeletons on PriceBadges: 
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/a8bebaaf-5fa5-4bc3-bc91-9881908e91cd)

- [x] Close tx modals after tx is signed and submitted:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/67d8215f-c1f1-4669-835e-2c915e6eeb75)

- [x] Don't close modals when Approval txs are sent, signed, or pending

 - [x] Switch to a `btn-primary` instead of a `btn-outline` for "Open [position]" buttons:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/222a22e8-e509-47c9-8434-40cd826d6ff9)

- [x] Adjust "Close [position]" button so it's relative in size and and shape to the "Open [position]" button
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/ef459852-6d12-463b-b62b-8cee5a8051d8)

- [x] Add CTA `action` prop for empty Long, Short, and LP, states @jackburrus 

- [x] Disallow negative numbers and exponential abbreviations (`1e23`)
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/16b96cb5-b680-4219-a763-af8560b6ea2a)

- [x] Improve UX in approval modal for custom amount:

> Small nit, UI-wise, seeing 'DAI' greyed out for the custom amount was confusing
> I can click 'Unlimited', and '1000 DAI' directly to select it, but I couldn't click 'DAI 0' to select it

https://images-ext-2.discordapp.net/external/vxTBmCCq4uH6LCIjn-zYvZRWvmiX54REA26X2Z0-qpU/https/i.gyazo.com/5ac74e05abce31cc1497090e6295da50.gif?width=770&height=644

- [x] Move logo and connect button into same column as content:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/033152b1-da50-4c82-9e70-441087d00504)

- [x] Rename `Transactions` to `All Transactions`

- [x] Add rust sdk method to calculate available liquidity:
https://discord.com/channels/754739461707006013/1062553591988113489/1219299567930183892

- [x] Add token icon in input:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/883a6b8b-2552-4b1b-b972-b195772cb379)

- [x] Show withdrawal shares in `Remove Liquidity` transaction row:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/03ebba08-df84-4561-a7e8-9fd33b00162e)

- [x] Fix z-index on toasts when modal is open:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/abefde22-5d47-4b7d-8813-895ee29f3a69)

- [x] Consistent capitalization across all labels and headers, eg: Longs and Shorts (not all captured in screenshot)
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/8c02ad31-e158-4577-9528-c5bff673788a)

- [x] Make tab section outlines the same color/opacity as the market stats outlines:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/4b4e4f18-1dbf-409f-bf20-583becf7f9a1)

- [x] Show shares balance in Your Balance card:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/7e8693ee-f395-4da1-a2f4-03da411dfea1)

- [x] Remove assets that you can't interact with from modal forms:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/25a630c1-3f41-4105-becd-766a868062f5)

- [x] Move "Mint" "View allowances" and "Revoke allowances" into its own modal:
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/90dec889-c09f-41a8-a492-41153babca27)
