### ISSUE TITLE
Testnet prep checklist

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#821]
- [ ] Update fonts and line-heights Typography: https://www.figma.com/file/zrgc0mEZ8yCC819ML3gmtu/Hyperdrive-UI-Kit-(v2---March-2024)-%E2%80%93-Internal-Use?type=design&node-id=1-3&mode=design&t=pHZIFSvypS5N58cF-0

- [x] Paginate Open/Closed long, short, and lp tables

- [x] Add chain identifier to navbar: 
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/28a47878-7000-4786-9247-bff17b73eaca)

- [x] Update FAQ (@DannyDelott)

- [x] Update links in footer and to docs on landing page
- [x] Add favicon
