### ISSUE TITLE
Rage Cage II Checklist

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#835]
- [x] Trading volume stuck at 0% 
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/29677d39-8c11-42c8-9588-52617d9eb7d2)

- [x] Make all links to docs open in a new tab

- [x] Trading Volume, show stale while revalidate

- [x] Dismiss success toasts after 10s

- [x] Move toasts into corner

- [x] Toast should track the tx and re-render instead of toasting twice, also should include failed tx 

![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/f88446a9-1c85-4764-9243-90cb0d0dfc9f)

- [x] #838

- [x] New label for "Slippage Paid"/"Positive Slippage" in Add/Remove LP modals

- [x] App Crash: "Rate must be non-negative": https://discord.com/channels/754739461707006013/1222612259998535760/1222619177504997550

- [x] LP Card shows `-0` pnl: 
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/f5324bc6-cbdc-4613-9f27-809767808f12)

- [x] Rounded button for pagination component

- [x] Add RevokeAllowanceModal @jackburrus 

- [x] More spacing between toasts on smaller screens: https://discord.com/channels/754739461707006013/1222612259998535760/1222620898649968881

- [x] Confirm slippage calc is correct (pair with @jrhea for repro): https://discord.com/channels/754739461707006013/1222612259998535760/1222621301588627548
Context: "i added liquidity at 3.5 fixed and 3.5 variable. the slippage for adding liquidity was like 0.9 eth. i immediately removed and get slippage of 8.6 steth"

- [x] Add base token and shares token icons to Market Header

- [ ] Add "Open a [L/S/LP], switch wallets, view your closed [L/S/LP] positions, **or explore other markets.**" To empty states on Longs/Shorts/LP

- [x] Disable button in Close Short when no input given: https://discord.com/channels/754739461707006013/1222612259998535760/1222622824787873903

- [x] Max button should be the user's balance if it's less than the pool's max, or the pool's max if the user has more money than the pool: https://discord.com/channels/754739461707006013/1222612259998535760/1222623064412389477

- [x] Default sort Tx table by most recent

- [x] Remove sort by Account on Tx table

- [x] Fix bug causing Size column sorting in tx table to not work
